#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
# 수정일 2022.11.30 mysql변환

spring:
  datasource:
    username: root
    password: Hangeul0223!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/GyerimWestValley

#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/GyerimWestValley?serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
# show_sql: true 는 system.out 에서 출력해주기 때문에 주석처리.

logging:
  level:
    org.hibernate.SQL: debug # hibernate에서 생성하는 모든 sql이 debug에서 보임
    org.hibernate.type: trace # 파라미터에 어떤값이 들어갔는지 확인할 수 있다.
